### ISSUE TITLE
Entries can be added with 0 values

### ISSUE THREAD

**Issue by smilepl0x** [jestercruz/fitness-tracker#9]
![image](https://user-images.githubusercontent.com/47682247/169169867-8b4ddeb9-7063-414f-8f6b-4a5332e7da23.png)

**Comment by jestercruz** [comment]
I think weight can be fine with an entry of 0. Some exercises (i.e. pushups) may not have additional weight. I will fix the sets and reps since they should at least be 1 each.

**Comment by smilepl0x** [comment]
Ah, good point. Maybe a checkbox or something the user can use to indicate it's an exercise that doesn't need a weight?
